# Generated by Django 5.1 on 2024-10-07 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Obligatorio', max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('common_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='blog.common_info')),
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('blog.common_info',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('common_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='blog.common_info')),
                ('id_tag', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('blog.common_info',),
        ),
    ]
